---
title: "Final Project"
author: "Yiqian Xin, Laiang Yao & Yun YUan"
date: "2/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Part Two:Data  
## Preparation

```{r}
# Load packages
library(tidyverse)
library(dataReporter)
```


```{r}
# Import data
load("../data/HAALSI_baseline_dataverse_14Apr2017.RData")
haalsi <- x %>%
  select(prim_key, cm069, cm070, cm071, hv019, hv020, hv021, hv022, hv003, hv005, cm014, bd002, bd003, bd036, c_bd_country, c_bd_educ4, rsex)

head(haalsi)
```
## Data wrangling
```{r}
# Tabulation
# table(haalsi$cm069, useNA = "always")
# table(haalsi$cm070, useNA = "always")
# table(haalsi$cm071, useNA = "always")
# table(haalsi$hv019, useNA = "always")
# table(haalsi$hv020, useNA = "always")
# table(haalsi$hv021, useNA = "always")
# table(haalsi$hv022, useNA = "always")
# table(haalsi$cm014, useNA = "always")
# table(haalsi$bd003, useNA = "always")
# table(haalsi$c_bd_educ4, useNA = "always")
# table(haalsi$c_bd_country, useNA = "always")
```

```{r}
# Wrangling
baseline <- haalsi %>%
  mutate(alc_consumption = recode(cm069, 
                                  "1 (YES) Yes" = 1,
                                  "2 (NO) No" = 0),
         alc_freq = recode(cm070,
                           "5 Less than once per month" = 1,
                           "4 1-3 days per month" = 2,
                           "3 1-4 days per week" = 3,
                           "2 5-6 days per week" = 4,
                           "1 Daily" = 5),
         alc_amount = recode(cm071,
                             "1 less than 1 " = 1,
                             "2 1-2" = 2,
                             "3 3-4" = 3,
                             "4 5 or more" = 4),
         sex_risk = recode(hv019,
                           "1 Yes" = 1,
                           "2 No" = 0
                           # "3 I do not remember" = NA
                           ),
         sex_work = recode(hv020,
                           "1 (YES) Yes" = 1,
                           "2 (NO) No" = 0),
         sex_work_condom = recode(hv021,
                                  "1 Yes" = 1,
                                  "2 No" = 0
                                  # "3 I do not remember" = NA
                                  ),
         sex_hiv = recode(hv022,
                          "1 (YES) Yes" = 1,
                          "2 (NO) No" = 0),
         sex_partners = hv003,
         sex_partners_24 = hv005,
         hiv_positive = recode(cm014,
                               "1 (YES) Yes" = 1,
                               "2 (NO) No" = 0),
         age = bd002,
         sex = rsex, 
         marital_status = case_when(bd003 %in% c("1 Never married",
                                                 "3 Separated/Deserted",
                                                 "4 Divorced",
                                                 "5 Widowed") ~ 0,
                                    bd003 == "2 Currently married or living with partner" ~ 1)) %>%
  select(prim_key, sex, alc_consumption, alc_freq, alc_amount,
         sex_risk, sex_work, sex_work_condom, sex_hiv,
         sex_partners, sex_partners_24, hiv_positive,
         age, marital_status, c_bd_country, c_bd_educ4)

# baseline$alc_consumption <- factor(baseline$alc_consumption)
# baseline$alc_freq <- factor(baseline$alc_freq)
# baseline$alc_amount <- factor(baseline$alc_amount)
# baseline$sex_risk <- factor(baseline$sex_risk)
# baseline$sex_work <- factor(baseline$sex_work)
# baseline$sex_work_condom <- factor(baseline$sex_work_condom)
# baseline$sex_hiv <- factor(baseline$sex_hiv)
# baseline$hiv_positive <- factor(baseline$hiv_positive)
# baseline$marital_status <- factor(baseline$marital_status)



baseline$alc <- baseline$alc_freq
baseline$alc[baseline$alc_consumption == 0] <- 0
baseline$alc <- factor(baseline$alc,
                       labels = c("Never", "Less than once per month", 
                                  "1-3 days per month", "1-4 days per week",
                                  "5-6 days per week", "Daily"))
baseline$sex_risk <- factor(baseline$sex_risk,
                            labels = c("No",
                                       "Yes"))
baseline$sex_hiv <- factor(baseline$sex_hiv,
                            labels = c("No",
                                       "Yes"))
baseline$sex <- factor(baseline$sex,
                       labels = c("Male", "Female"))

```

## Create codebook
```{r include = FALSE}
# makeCodebook(baseline, replace=TRUE)
```


## Preliminary exploration and visulization
```{r Figure 1}
# Fig. 1. Descriptive analysis of alcohol consumption
# https://twitter.com/jennagoldd_/status/1354230989736837122
# https://github.com/Jenna-Gold/TidyTuesday/blob/main/Plastics/Code.R

# Recode alc_consumption and alc_freq into one variable. 
# table(baseline$alc_consumption, useNA = "always")
# table(baseline$alc_freq, useNA = "always")
# baseline$alc <- baseline$alc_freq
# baseline$alc[baseline$alc_consumption == 0] <- 0
# table(baseline$alc, useNA = "always")
# baseline$alc <- car::recode(baseline$alc,
#                                     "0 = '0 Never';
#                                     1 = '1 Less than once per month';
#                                     2 = '2 1-3 days per month';
#                                     3 = '3 1-4 days per week';
#                                     4 = '4 5-6 days per week';
#                                     5 = '5 Daily'")

  # ggplot(data = subset(baseline, !is.na(alc)), aes(x = alc)) +
  #   geom_bar() + 
  #   theme_minimal() + 
  #   labs(x = 'Frequency of alcohol consumption',
  #     y = 'Number',
  #     title='How often do you have at least one alcoholic drink?') +
  #   theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  #   scale_y_continuous(breaks = seq(from = 0, to = 1200, by = 100))
  

  color_palette <- 
  c(
    "#000000",
    "#34D987",
    "#00C58E",
    "#00B094",
    "#009B96",
    "#008695",
    "#007090",
    "#3272A2"
  )
  

  fig1 <- baseline %>% 
    subset(!is.na(alc)) %>%
    group_by(alc) %>%
    summarise(n = n()) %>% 
    mutate(alc_prop = n/sum(n, na.rm = TRUE), 
           alc_pct = round(100 * alc_prop, 0)) 
    
    

p1 <- ggplot(data = fig1, aes(x = rev(alc), y = alc_prop)) +
  geom_bar(aes(fill = alc), stat="identity") +
  geom_text(hjust = 1, 
            # size = 3,
            # color = "white",
            aes( y = 0,
                 label = paste(alc,":", n, "(", alc_pct, "%)"))) +
  theme_void() +
  theme(
        text = element_text(family = "Tahoma"),
        plot.title = element_text(
          hjust = 0,
                                  face = "bold",
                                  size= 24,
                                  # color = "white"
          ),
        plot.subtitle = element_text(
          hjust = 0,
                                     size = 18,
                                     # color = "white"
          ),
        strip.text = element_text(
          # color = "white",
                                  size = 12),
        plot.caption = element_text(
          # color = "white",
                                    hjust = 0,
                                    size = 12),
        legend.position = "none"
        # panel.background = element_rect(fill =  "black"),
        # plot.background = element_rect(fill = "black"),
        ) + 
  scale_fill_manual(values = c(# "#000000",
                              # "#34D987",
                              "#00C58E",
                              "#00B094",
                              "#009B96",
                              "#008695",
                              "#007090",
                              "#3272A2"
  )) +
  labs(
    title = "Frequency of alcohol consumption",
    subtitle = "How often do you have at least one alcoholic drink?"
    ) + 
  coord_polar(theta = "y") +
  ylim(0, 1)
  # +
  # facet_wrap(~ Continent) 
  
p1

  ggsave(
  here::here("Figures", "fig1.png"),
  p1,
  width = 10,
  height = 9
  )
  

```

```{r Figure 2}
# Fig. 2. Descriptive analysis of condom use (2 variables)
# Use sex_risk/hv019 and sex_hiv/hv022. 
# sex_risk/hv019 - Have you had vaginal or anal sex without a condom when you were drunk or buzzed on alcohol or high on any other drug?
# sex_hiv/hv022 - Have you ever had sex without a condom with someone you know is HIV positive?

table(baseline$sex_risk, useNA = "always")
table(baseline$sex_hiv, useNA = "always")



library(patchwork)
# p2 <- ggplot(data = subset(baseline, !is.na(sex_risk)), aes(x = sex_risk)) +
#     geom_bar()
# p3 <- ggplot(data = subset(baseline, !is.na(sex_hiv)), aes(x = sex_hiv)) +
#     geom_bar()
  fig2_1 <- baseline %>% 
    subset(!is.na(sex_risk)) %>%
    group_by(sex_risk) %>%
    summarise(n = n()) %>% 
    mutate(sex_yn = sex_risk, 
           sex_prop = n/sum(n, na.rm = TRUE), 
           sex_pct = round(100 * sex_prop, 0), 
           sex_cat = "sex_risk") %>%
    select(-c(sex_risk))
  
  fig2_2 <- baseline %>% 
    subset(!is.na(sex_hiv)) %>%
    group_by(sex_hiv) %>%
    summarise(n = n()) %>% 
    mutate(sex_yn = sex_hiv, 
           sex_prop = n/sum(n, na.rm = TRUE), 
           sex_pct = round(100 * sex_prop, 0), 
           sex_cat = "sex_hiv") %>%
    select(-c(sex_hiv))
  
  fig2 <- rbind(fig2_1, fig2_2)

# ggplot(fig2, aes(x = sex_cat, y = sex_prop, fill = sex_yn)) +
#   geom_col() +
#   scale_fill_viridis_d() +
#   coord_polar("y")
  
p2 <- ggplot(data = fig2, aes(x = sex_cat, y = sex_prop)) +
  geom_col(aes(fill = sex_yn), stat="identity") +
  geom_text(aes(label = paste(n, "(", sex_pct, "%)")), 
            position = position_stack(vjust = .5), 
            # color="white", 
            # size=3, 
            hjust = 0
            ) + 
  # geom_text(
  #   hjust = 1,
  #           size = 3,
  #           color = "white",
  #           aes( 
  #             y = 0,
  #                label = paste(n, "(", sex_pct, "%)"))) +
  theme_void() +
  theme(
        text = element_text(family = "Tahoma"),
        plot.title = element_text(
          hjust = 0,
                                  face = "bold",
                                  size= 24,
                                  # color = "white"
          ),
        plot.title.position = "plot", 
        # plot.subtitle.position = "plot", 
        plot.subtitle = element_text(
          hjust = 0,
                                     size = 18,
                                     # color = "white"
          ),
        strip.text = element_text(
          # color = "white",
                                  size = 12),
        plot.caption = element_text(
          # color = "white",
                                    hjust = 0,
                                    size = 12),
        legend.text = element_text(
          # color = "white",
                                  size = 12),
        legend.title= element_blank(), 
        # legend.position = "none",
        # panel.background = element_rect(fill =  "black"),
        # plot.background = element_rect(fill = "black"),
        ) + 
  scale_fill_manual(values = c(# "#000000",
                              # "#34D987",
                              "#00C58E",
                              # "#00B094",
                              "#009B96"
                              # "#008695",
                              # "#007090",
                              # "#3272A2"
  )) +
  labs(
    title = "Descriptive analysis of condom use",
    subtitle = "Have you had vaginal or anal sex without a condom when you\nwere drunk or buzzed on alcohol or high on any other drug?\nHave you ever had sex without a condom with someone you\nknow is HIV positive?"
    ) + 
  coord_polar(theta = "y") +
  ylim(0, 1)

  
p2

  ggsave(
  here::here("Figures", "fig2.png"),
  p2,
  width = 10,
  height = 9)
  
p1 + p2
  
p12 <- p1 + p2

p12

  ggsave(
  here::here("Figures", "fig12.png"),
  p12, 
  width = 16,
  height = 9)
  
```

```{r Figure 3}

#===============================================================================
# Fig. 3. Descriptive analysis of sexual partners (2 variables)
# Use sex_partners/hv003 and sex_partners_24/hv005.
# sex_partners/hv003 - How many different sexual partners have you had in your lifetime?
# sex_partners_24/hv005 - During the last 24 months (that is since ^FLHV005), how many sexual partners have you had?
table(baseline$sex_partners, useNA = "always")
table(baseline$sex_partners_24, useNA = "always")




# gghistogram(
#   baseline, x = "sex_partners", y = "..density..",
#   add = "mean", rug = TRUE,
#   fill = "sex", palette = c("aquamarine2", "coral1"),
#   add_density = TRUE
#   )

library(ggpubr)
library(cowplot)
# 1. Create the histogram plot
  p3 <- gghistogram(
  baseline, x = "sex_partners", 
  add = "mean", 
  # rug = T,
  fill = "sex", 
  color = "sex", 
  palette = c("#00C58E", "#e9da8e"), 
  title = "Distribution of the number of sexual partners had in one's lifetime",
  xlab = "Number of sexual partners",
  ylab = "Count")
  
  
#cfa20e
#d7b543

#dfc869

#e9da8e

#f3ecb3

#fffdd8
  
  p3
  
  ggsave(
  here::here("Figures", "fig3.png"),
  p3, 
  width = 16,
  height = 9)
  
  # p3_2 <- gghistogram(
  # baseline, x = "sex_partners_24", 
  # add = "mean", 
  # # rug = T,
  # fill = "sex", 
  # color = "sex", 
  # palette = c("aquamarine2", "coral1"))
  # 
  # p3_1 + p3_2

# 2. Create the density plot with y-axis on the right
# Remove x axis elements
# pdensity <- ggdensity(
#   baseline, x = "sex_partners",
#   color= "sex", palette = c("aquamarine2", "coral1"),
#   alpha = 0
# ) +
#   scale_y_continuous(expand = expansion(mult = c(0, 0.05)), position = "right")  +
#   theme_half_open(11, rel_small = 1) +
#   rremove("x.axis")+
#   rremove("xlab") +
#   rremove("x.text") +
#   rremove("x.ticks") +
#   rremove("legend")

# 3. Align the two plots and then overlay them.
# aligned_plots <- align_plots(phist, pdensity, align="hv", axis="tblr")
# ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])




# ggplot(data = baseline, mapping = aes(x = sex_partners)) +
#   geom_histogram(
#                  colour = 1, fill = "white") +
#   geom_density(aes(y = 2 * ..count..))
# 
# ggplot(data = baseline, mapping = aes(x = sex_partners_24)) +
#   geom_histogram(aes(y = ..density..),
#                  colour = 1, fill = "white") +
#   geom_density(lwd = 1, colour = 4,
#                fill = 4, alpha = 0.25)
# 
# library(see)
# 
# ggplot(data = subset(baseline, !is.na(sex_risk)),
#        aes(x= sex_risk, y = sex_partners, fill = sex_risk)) + 
#   
#   geom_boxplot(width = 0.1,
#                position = position_nudge(x = -0.3, y = 0),
#                outlier.shape = 21,
#                show.legend = FALSE) + 
#   # scale_fill_manual(values=c("#BE3639", "#0A9B9C", "#BE3639","#0A9B9C")) + 
#   
#   geom_violindot(size_dots = 8,
#                  trim = FALSE,
#                  show.legend = FALSE) +
# 
# # custom labels
#   labs(
#     title = 'Perceived stress scales between Control and Yoga group',
#     subtitle = 'Data distribution, Median, Inter quartile range, Scatter plot',
#     caption = 'Data: Scholar | PhD work',
#     x = ' ', 
#     y = 'Perceived Stress Scale'
#   ) + 
#   
#   theme(
#     plot.title = ggtext::element_markdown(),
#     plot.caption = ggtext::element_markdown(),
#     axis.title.x = ggtext::element_markdown(),
#     axis.title.y = ggtext::element_markdown()
#   )

  
# 
# # Data
# set.seed(5)
# x <- rnorm(1000)
# df <- data.frame(x)
# 
# # Histogram with kernel density
# ggplot(df, aes(x = x)) + 
#   geom_histogram(aes(y = ..density..),
#                  colour = 1, fill = "white") +
#   geom_density(lwd = 1, colour = 4,
#                fill = 4, alpha = 0.25) 
```



